### ISSUE TITLE
less verbose error message when missing/incorrect config

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/py-cifsdk#58]
```
cif -q example.com -C /home/giovino/.ciff.yml
Traceback (most recent call last):
  File "/home/giovino/code/py-cifsdk/venv/bin/cif", line 9, in <module>
    load_entry_point('py-cifsdk==0.0.3-20-ge4992ad', 'console_scripts', 'cif')()
  File "/home/giovino/code/py-cifsdk/py-cifsdk/cifsdk/client.py", line 245, in main
    o = read_config(args)
  File "/home/giovino/code/py-cifsdk/py-cifsdk/cifsdk/utils.py", line 22, in read_config
    raise Exception("Unable to read {} config file".format(args.config))
Exception: Unable to read /home/giovino/.ciff.yml config file
```

Not raise an Exception?

**Comment by wesyoung** [comment]
i can see it both ways, but i'm becoming of the opinion that when in doubt, raise... if you try to try/catch too deep in python, strange things happen.

if we don't want the output, we should raise deeper in the client, but catch that specific raise higher up and log out there (instead of deeper in the client).
